In [1]:
import cv2

In [2]:
im_g = cv2.imread('smallgray.png',0)

In [3]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
im2 = cv2.imread('smallgray.png',1)

In [9]:
im2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
cv2.imwrite('new_image_grey.png',im_g)

True

In [12]:
im3 = cv2.imread('diana.jpg',0)

In [13]:
cv2.imwrite('new_image_grey2.png',im3)

True

In [21]:
im3[1:4,0:2]

array([[57, 57],
       [56, 57],
       [57, 57]], dtype=uint8)

In [24]:
im3.flat

In [26]:
a = []
for i in im3.flat:
    a.append(i)

In [28]:
len(a)

343040

In [29]:
import numpy as np

In [32]:
im3 = np.hstack((im_g,im_g))

In [33]:
im3

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [36]:
im3 = np.vstack((im_g,im_g))

In [37]:
im3

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
im4 = np.vsplit(im3,6)

In [46]:
im4[0]

array([[187, 158, 104, 121, 143]], dtype=uint8)

In [47]:
import numpy

In [48]:
import pandas

In [49]:
import sys

print(sys.executable)

C:\Users\Master\Anaconda3\python.exe
